#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

NODE_TYPE=worker \
HEAD_NODE_IP=100.100.1.4 \
VLLM_HOST_IP=100.100.1.5 \
HF_HOME=/home/ege/.cache/huggingface \
NCCL_SOCKET_IFNAME=tailscale0 \
docker compose -f "${SCRIPT_DIR}/docker-compose.yaml" up --build
